### ISSUE TITLE
Footer touches body if body is too short?

### ISSUE THREAD

**Issue by 9034725985** [noraj1337/mkdocs-windmill-dark#1]
Example here 

https://kuairmail.gitlab.io/#001-how-did-we-get-here/ 

![screenshot from 2017-12-27 06-36-20](https://user-images.githubusercontent.com/1676445/34380547-47f2e446-ead0-11e7-850f-6fb9e4daa234.png)

**Comment by 9034725985** [comment]
can't reproduce on iMac though... 

<img width="2560" alt="screen shot 2017-12-28 at 11 25 52 am" src="https://user-images.githubusercontent.com/1676445/34416539-f5c4895c-ebc1-11e7-90d7-879ffd2eea03.png">
<img width="2560" alt="screen shot 2017-12-28 at 11 25 49 am" src="https://user-images.githubusercontent.com/1676445/34416540-f5cd6a40-ebc1-11e7-88b7-b4c22a1070ae.png">
<img width="2560" alt="screen shot 2017-12-28 at 11 25 46 am" src="https://user-images.githubusercontent.com/1676445/34416541-f5d88f88-ebc1-11e7-8c71-e542d542e246.png">
<img width="2560" alt="screen shot 2017-12-28 at 11 25 43 am" src="https://user-images.githubusercontent.com/1676445/34416542-f5e5727a-ebc1-11e7-981c-9bbdd9836a43.png">

**Comment by 9034725985** [comment]
I can reproduce it if I am not full screen though 

<img width="1502" alt="screen shot 2017-12-28 at 11 29 12 am" src="https://user-images.githubusercontent.com/1676445/34416637-61800a72-ebc2-11e7-9565-94ba57266e5b.png">
<img width="1502" alt="screen shot 2017-12-28 at 11 29 08 am" src="https://user-images.githubusercontent.com/1676445/34416638-618a3510-ebc2-11e7-88ca-782dbdc85509.png">
<img width="1502" alt="screen shot 2017-12-28 at 11 29 03 am" src="https://user-images.githubusercontent.com/1676445/34416639-6192838c-ebc2-11e7-8444-0ed3ceda0b72.png">
<img width="1502" alt="screen shot 2017-12-28 at 11 28 59 am" src="https://user-images.githubusercontent.com/1676445/34416640-619cf448-ebc2-11e7-9b65-a82023fd367f.png">

**Comment by noraj** [comment]
@9034725985 Thank for reporting this bug.

1) An easy workaround is to disable the nav bottom like I did on my [ruby cheatsheet](https://noraj.gitlab.io/ruby-cheatsheet/) (see in the [mkdocs.yml](https://gitlab.com/noraj/ruby-cheatsheet/blob/master/mkdocs.yml)).

2) As you can see [mkdocs-windmill-dark](https://github.com/noraj1337/mkdocs-windmill-dark) is a fork from [mkdocs-windmill](https://github.com/gristlabs/mkdocs-windmill). I found the breaking change came from this commit (https://github.com/gristlabs/mkdocs-windmill/commit/d55a10aa7c4f4591027148362f398c1bfe6abeae#diff-e087fcb392dcfff81191bd345dcde84c).

Let me see if I can fix the CSS.

**Comment by noraj** [comment]
Fixed in this commit: https://github.com/noraj1337/mkdocs-windmill-dark/commit/31ae56e7061565e59e2df49b7eb65cafc43d7954 without regressing to https://github.com/gristlabs/mkdocs-windmill/issues/4
