### ISSUE TITLE
Improper theme citation.

### ISSUE THREAD

**Issue by haxys** [noraj1337/mkdocs-windmill-dark#4]
At the bottom of my page, we have the following text:

```
Documentation built with [MkDocs](http://www.mkdocs.org/) using [Windmill Dark]({{repo_url}}) theme by {{site_author}} (noraj).
```

The `{{repo_url}}` and `{{site_author}}` sections should include information for the Windmill Dark theme and its creator. However, these sections are auto-populated from the `mkdocs.yml` file, resulting in the `Windmill Dark` link pointing to the wrong repo, and the theme designer being listed as the author's name instead of the designer's name. For example, on [ScriptSharks.com](https://scriptsharks.com/), the citation reads:

```
Documentation built with [MkDocs](http://www.mkdocs.org/) using [Windmill Dark](https://github.com/scriptsharks/scriptsharks.source) theme by Christopher M. Steffen (noraj).
```

`Windmill Dark` links to the ScriptSharks source repo, instead of the theme repo, and the theme author is listed as `Christopher M. Steffen` instead of the actual theme author.

These values should not be populated from `mkdocs.yml`, but instead should be static values set in the theme.

**Comment by noraj** [comment]
Thanks fixed
